# Generated by Django 4.2 on 2023-04-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_apparat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apparat',
            options={'verbose_name': 'Аппаратная процедура', 'verbose_name_plural': 'Аппаратные процедуры'},
        ),
        migrations.AlterModelOptions(
            name='complex',
            options={'verbose_name': 'Комплекс программ', 'verbose_name_plural': 'Комплекс программ'},
        ),
        migrations.AlterModelOptions(
            name='massage',
            options={'verbose_name': 'Массаж', 'verbose_name_plural': 'Массаж'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Акция', 'verbose_name_plural': 'Акции'},
        ),
        migrations.AddField(
            model_name='complex',
            name='task',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
